global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.35.191:8080']
        labels:
          application: 'reservation'

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.35.5:8071','192.168.35.5:8072','192.168.35.5:8073']
        labels:
          service: 'kafka'

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['192.168.35.179:9104']
        labels:
          database: 'mysql'