spring.application.name: rsaga.reservation


kafka:
  bootstrap-servers: "192.168.35.5:9092,192.168.35.5:9093,192.168.35.5:9094"
  schema-registry-url: "http://192.168.35.5:8081"

logging:
  level:
    io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializerConfig: WARN