spring.application.name: reservation.item

spring:
  datasource:
    url: jdbc:mysql://192.168.35.179:3306/reservation-saga
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: master

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG